version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  server:
    build:
      context: .
    ports:
      - 80:3000
    depends_on:
      - postgres
